### ISSUE TITLE
path needs to be updated

### ISSUE THREAD

**Issue by peterhack** [dynatrace-innovationlab/dynatrace-monitoring-as-service#1]
Lab 2; Step 4 states 'cd to jmeter-as-container', however this should actually be 'cd to /dynatrace-monitoring-as-service/jmeter-as-container'.

**Comment by jetzlstorfer** [comment]
please go ahead and fix this directly in the readme and create a pull request. thx :)

**Comment by jetzlstorfer** [comment]
updated the path, closing this issue
